### ISSUE TITLE
custom site sort order

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234-new/bypass-paywalls-firefox-clean#3]
my custom sites are still not sorted alphabetically

**Comment by magnolia1234-new** [comment]
> my custom sites are still not sorted alphabetically

Click the sort-button in custom sites-options and then save.

**Comment by danielgruber8** [comment]
Apologies for being a n00b, I didn't notice the new sort button ... as I just looked at the list. 
Assumed it would sort automatically

**Comment by magnolia1234-new** [comment]
> Apologies for being a n00b, I didn't notice the new sort button ... as I just looked at the list.
> Assumed it would sort automatically

That's the default behaviour of Chrome, but in Firefox someone could still prefer the chronological order.
