### ISSUE TITLE
Not working on lemonde.fr

### ISSUE THREAD

**Issue by MartinGraive** [magnolia1234-new/bypass-paywalls-firefox-clean#5]
It looks like the extension is failing to bypass Le Monde's paywall.

**Comment by qnoum** [comment]
Same by me:

Il vous reste 85.24% de cet article à lire. La suite est réservée aux abonnés.

The percentage may differ in other articles, 
but still pretty big part of the text seems to be blocked.

**Comment by danielgruber8** [comment]
do you have an article example? i tried it here from aussie and whilst i don't know any french the articles seem to load okay.

**Comment by magnolia1234-new** [comment]
Le Monde's fix is no longer working indeed.

**Comment by qnoum** [comment]
this article in particular, still the same 85.24% is hidden:
https://www.lemonde.fr/societe/article/2020/04/17/coronavirus-a-paris-voyages-au-bout-de-la-nuit_6036869_3224.html

and other paywalled are also likewise

**Comment by magnolia1234-new** [comment]
Yes I know, all premium articles.
They closed the Googlebot loophole.

**Comment by magnolia1234-new** [comment]
LeMonde.fr will be removed in next release.
