### ISSUE TITLE
banner removals

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234-new/bypass-paywalls-firefox-clean#6]
Please implement these banner removals if possible
https://github.com/iamadamdev/bypass-paywalls-chrome/commits?author=kimkha

Also Kansascity.com is another paper that has just been added on "the other" fork while you disappeared ;)

**Comment by magnolia1234-new** [comment]
If you want to read a local usa newspapers you can add it to custom sites.
Banners can be blocked by uBlock Origin though.
