### ISSUE TITLE
Why the new repository?

### ISSUE THREAD

**Issue by sanjayen** [magnolia1234-new/bypass-paywalls-firefox-clean#7]
Thank you for this addon. I was refreshing the old repository for the past day and it was giving a 404.

What was the reason for this?

Keep up the good work.

**Comment by magnolia1234-new** [comment]
Old account might be suspended forever, but I'm content with a fresh/cleansed repo.
Would be nice for users to be able to update/redirect to new repo though (wait and see).

**Comment by sanjayen** [comment]
Thank you for explaining. Look forward to more releases.
