### ISSUE TITLE
Not working on ilmessaggero.it

### ISSUE THREAD

**Issue by gioxx** [magnolia1234-new/bypass-paywalls-firefox-clean#8]
Hi. If you try to visit a paywall content on ilmessaggero.it you obtain the popup to subscribe premium offer.
I'll give you an example: https://www.ilmessaggero.it/pay/edicola/coronavirus_app_immuni_come_funziona-5182401.html

Just to add a (I think) useful information: using Anti-Messaggero addon on Firefox (https://addons.mozilla.org/it/firefox/addon/anti-messaggero/?src=search) all works well and I can read the blocked content.

Thanks.

**Comment by magnolia1234-new** [comment]
Working fine for me, just the annoying overlay with video-popup (I'll add a fix for this).

**Comment by danielgruber8** [comment]
you always do magic. 
you're the david copperfield of coding. 
im shocked that google/apple/microsoft hasn't hired you.

**Comment by magnolia1234-new** [comment]
@gioxx Do you have a screenshot of the 'paywall' you see (without anti-messaggero)?

**Comment by gioxx** [comment]
Sure: https://imagehosting.altervista.org/images/2020/04/22/5e32a88dc10109c12a99a322d83c2794.png

**Comment by magnolia1234-new** [comment]
Weird, I've never seen the paywall.
Did you enable the site in the BPC-options?

**Comment by gioxx** [comment]
Of course! And I tell you more: your addon seems to be active on the webpage but without solve the problem and without overcoming the obstacle.

Take a look:
http://prntscr.com/s45y9v
http://prntscr.com/s45ynu

**Comment by magnolia1234-new** [comment]
Paywall only pops up for me when I set my VPN-connection to Italy.
uBlock Origin's filterlist 'Fanboy's Enhanced Tracking List' blocks it then, but I'll block the paywall-script to BPC in the next release.

**Comment by gioxx** [comment]
Thanks! 😄

**Comment by gioxx** [comment]
I have updated to 1.7.0.3 but the problem is not solved. I can see again the paywall popup and can't go forward or exclude that to read the article. If I try to close the popup the website force me to redirect to the home page.

**Comment by magnolia1234-new** [comment]
Only in new release (probably tonight).

**Comment by gioxx** [comment]
Got it, I'll wait for it 😄

**Comment by magnolia1234-new** [comment]
Check fix in new release v1.7.0.4.
