### ISSUE TITLE
likeminded project - paywallr

### ISSUE THREAD

**Issue by qnoum** [magnolia1234-new/bypass-paywalls-firefox-clean#9]
Maybe you know about paywallr made by tobimori. 
It specialises on german local newspapers: 
https://github.com/tobimori/paywallr
Perhaps some sites could be added here or tips from there turn out helpful.
Cheers

**Comment by magnolia1234-new** [comment]
I just tested the major site Frankfurter Allgemeine (Faz.net) and the addon is not working on premium articles.
Have you tested any of the other (local) sites?

**Comment by qnoum** [comment]
For me it all including Faz works only in Chrome,
which is a shame as I like FF more.

**Comment by magnolia1234-new** [comment]
Interesting fix indeed.

**Comment by qnoum** [comment]
update: the last version 2.2.1 works even in Firefox.

**Comment by magnolia1234-new** [comment]
Paywallr is indeed working on Firefox too now, but layout ('just' text) is completely gone though (quick-fix).
It's also working for me in BPC (locally).
Btw I didn't know that m.faz.net was free on a mobile phone (or mobile user-agent).

**Comment by magnolia1234-new** [comment]
Frankfurter Allgemeine (Faz.net) will be added in next release (you may test it as a temporary add-on or zip your own unsigned xpi-file which can be used in Firefox development build).

I updated the script from paywallr (@tobimori).
Also compatible with Firefox now (regex lookbehind not supported on FF).

**Comment by tobimori** [comment]
Well, m.faz.net is not free on mobile, but they save the complete article in meta data (json-ld) as described [here](https://github.com/tobimori/paywallr#frankfurter-allgemeine-zeitung). Firefox addon didn't work because of unsupported lookbehinds.

**Comment by tobimori** [comment]
@qnoum Which articles do you mean by zeitung.faz.net? I couldn't get any article from there without logging in first.

**Comment by magnolia1234-new** [comment]
> Well, m.faz.net is not free on mobile, but they save the complete article in meta data (json-ld) as described [here](https://github.com/tobimori/paywallr#frankfurter-allgemeine-zeitung). Firefox addon didn't work because of unsupported lookbehinds.

Not exactly free on mobile indeed ;-)
Check my updated regex-code (also for ä etc.).
Only exceptions needed for names like GlaxoSmithKline.

**Comment by tobimori** [comment]
Yes, it works perfectly. Thanks for your help!

**Comment by qnoum** [comment]
@tobimori 
> @qnoum Which articles do you mean by zeitung.faz.net? I couldn't get any article from there without logging in first.

When I go to zeitung.faz.net it shows some "kiosk" or whatever,
but if I switch to "zeitung" right from faz.net it redirects me here:
https://zeitung.faz.net/faz/seite-eins/?switchzeitung

For any article I click from there, it loads the title and brief annotation,
and underneath it loads complete article text though in encrypted form,
I can see it when viewing the page in "No style" mode.

And welt+ articles also work in the same way.

**Comment by tobimori** [comment]
@qnoum Sadly I can't figure out how they encrypt/decrypt these texts. I assume it's just random scrambled stuff.

**Comment by danielgruber8** [comment]
Are you going to merge all the other sites on paywallr to this project? 
If not, can both addons be used simultaneously as you have now added faz.net so will there be any conflicts in using both?

**Comment by magnolia1234-new** [comment]
Paywallr supports mainly local German newspapers (besides Faz.net).
I'm not going to add them all, but some are supported already by the general paywall-script block on Piano/TinyPass.
But there should be no problem by using multiple add-ons simultaneously.

**Comment by tobimori** [comment]
@danielgruber8 You should be fine adding both, just disable one of them on FAZ.NET.  You can disable paywallr sites by clicking on the Icon in the browser when you're on a locked site.

**Comment by magnolia1234-new** [comment]
Faz.net added in new release v1.7.0.4.
